### ISSUE TITLE
arreglar descripcion de articulos

### ISSUE THREAD

**Issue by MoralesRene** [lorenzoSanchez97/MercadoLiebre#1]
solo debe desaparecer el titulo del producto, el precio y descuento debe quedar estatico.

**Comment by lorenzoSanchez97** [comment]
A qué vista te referís? Mobile, tablet o desktop? En desktop el título del producto es lo único que desaparece (sólo aparece cuando pasas el mouse por encima). El precio y el descuento son estáticos, están siempre visibles. Te adjunto imágen:

![issue rene](https://user-images.githubusercontent.com/121801292/220671051-d14ba305-21a6-409a-b942-47732042431d.png)

**Comment by MoralesRene** [comment]
Perdon, se me cruzaron los issues, acá debía de poner que el carrusel solo se muestra en la vista home

**Comment by lorenzoSanchez97** [comment]
Ya lo corregí. Si te parece bien no olvides cerrar el issue.
