### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by Sowska** [lorenzoSanchez97/MercadoLiebre#2]
1. Contenga estos elementos cada sección - **Cumple**
2. Haciendo foco en los estilos del pie de página (Footer):
● ¿El contenido de todos los artículos está centrado?- **Cumple**
● ¿Los íconos tienen un tamaño de 2em y un margen inferior de separación de
10 píxeles? **Cumple**
3. ¿El sitio se adapta a distintas resoluciones de pantalla? **Cumple**
4. ¿El sitio cuenta con un formulario de registro de usuarios? **Cumple**
5. ¿El sitio cuenta con un formulario de login? **Cumple**
6. ¿Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios? **Cumple**
7. ¿El search bar es un formulario?   **Cumple**
8. ¿Se utilizan animaciones y propiedades de transición de CSS? **Cumple**
9. Para terminar el feedback, menciona algunas cosas que crees que tu
compañero hizo bien. **Es igual al mockup, muy acordes los tamaños de todas las imagenes y las proporciones de botones**
10. Por último, menciona algo que tu compañero podría mejorar. **Tal vez ver la forma de que las animaciones de la sombra de los productos en la version desktop no desplacen el elemento durante la interaccion. De todas formas no era requerimiento, está muy hermoso**

**Comment by lorenzoSanchez97** [comment]
En el punto 7 mencionas que el search bar no es un formulario. Sin embargo, lo hice dentro de una etiqueta form. Te adjunto imagen del código.
![issue sofi](https://user-images.githubusercontent.com/121801292/220668575-4ccc63cd-e10f-4217-be4d-c3438372d06c.png)

**Comment by Sowska** [comment]
perdon, vi mal! corregido

**Comment by lorenzoSanchez97** [comment]
Genial! No olvides cerrar el issue.
